### ISSUE TITLE
Automate iTunes Connect app update

### ISSUE THREAD

**Issue by duemunk** [bemyeyes/bemyeyes-ios#111]
- [x] Upload screenshots
- [x ] Update what's new/update text
- [x] Update app descriptions from CrowdIn

@simonbs You had some new found experience in this?

**Comment by simonbs** [comment]
I'm using fastlane and deliver to handle uploads. I am not sure whether or not it is suitable in this case but it could be worth trying out.

**Comment by duemunk** [comment]
I was thinking of trying that out. Seems to be the rave these days :)
What parts of fastlane have you used with success so far @simonbs?

**Comment by simonbs** [comment]
I've benefit much from using the snapshot, sigh, produce, ipa, deliver, frameit, increment_build_number, Crashlytics Beta and Slack actions.
