### ISSUE TITLE
Ability to call back if call can't connect or is dropped

### ISSUE THREAD

**Issue by Robdel12** [bemyeyes/bemyeyes-ios#14]
I was called upon to help someone but we couldn't connect. It was stuck at "waiting for the other party" until I disconnected after 3 mins of waiting. I wanted to try to call them back to see if I could help them but there's no method to do so right now.

**Comment by duemunk** [comment]
We would rather avoid the error in the first place. It's still the early days and we continue to improve the service, so we might get back to this depending on where we end up.
