### ISSUE TITLE
Help/skill set categories

### ISSUE THREAD

**Issue by Cowboy6480** [bemyeyes/bemyeyes-ios#143]
To make the connections more efficient, setting up an eyes/sighted skill set profile would allow the blind get higher quality help. 

•general help
•Mechanical
•cooking/food/groceries
•pets
•computers/digital devices
•Health
•Fashion
•Male/Female let's be real here and not get offended on separating gender. The reality is, help with menstrual products isn't for everyone from both the requestor and helper.

**Comment by duemunk** [comment]
We actually already have this one the road map here #100.
I'll close the issue but it will stay as a reference for the other issue.
