### ISSUE TITLE
Invalid `Podfile`

### ISSUE THREAD

**Issue by mamaral** [bemyeyes/bemyeyes-ios#16]
Just recently forked this and after running the initial `pod install` I received the following error:

`[!] Invalid 'Podfile' file: undefined method 'source' for #<Pod::Podfile:0x007f9d02832f88>. Updating CocoaPods might fix the issue. source 'https://github.com/CocoaPods/Specs.git'`

Commenting out the above line in attempting to debug the situation resulted in another error:

`[!] Unknown external source parameters for 'Reveal-iOS-SDK': '{:configurations=>["Debug"]}'`

I am on the latest release of Cocoapods, 0.35.0. Any ideas?

Commenting out both lines resulted in a successful pod install, but of course the project wouldn't compile without the required dependencies.

**Comment by jeremangnr** [comment]
They are using Cocoapods 0.36-pre

**Comment by mamaral** [comment]
I updated to the pre-release version and had the same issue. I will try again later to be sure.

**Comment by irodrigo17** [comment]
CocoaPods version is locked to 0.33.1 in Gemfile.lock, and 0.33.1 can't handle the `source 'https://github.com/CocoaPods/Specs.git'` line in the Podfile. 

CocoaPods 0.35 does handle it, but the Podfile.lock was indeed generated by 0.36.0.beta.1.

**Comment by jeremangnr** [comment]
Try updating Cocoapods to latest pre-release and then cloning the repo again. Don't use the same on which you tried to install with older pods

**Comment by mamaral** [comment]
@jeremangnr Just tried that and unfortunately the same issue exists. Updated to prerelease, deleted project folder from my computer, created new folder and cloned the repo fresh, and running `pod install` still fails with:

`[!] Invalid `Podfile` file: undefined method `source' for #<Pod::Podfile:0x007fed8a32bef8>. Updating CocoaPods might fix the issue.`

**Comment by irodrigo17** [comment]
@mamaral can you please double check your cocoapds version with pod --version before running pod install? You're probably using 0.33.1 even after running gem update cocoapds because of the Gemfile.lock file in this folder. 

The Gemfile.lock needs to be updated, as well as the Podfile.lock which was generated by cocoapods 0.36-pre, and will give you a warning when you run pod install with latest stable cocoapods version which is 0.35 now.

**Comment by mamaral** [comment]
@irodrigo17 Ahh yes indeed that is the case. There are a number of references to `cocoapods (0.33.1)` in the Gemfile.lock. What exactly should I change, and to what version?

**Comment by irodrigo17** [comment]
@mamaral Just deleting the Gemfile.lock and running bundle install again should do the trick. It should create a new Gemfile.lock with cocoapods 0.35 and all the dependencies updated.
Then you might need to delete the Podfile.lock before running pod install, it will also generate a new one with the installed cocoapods version.

You can find more information about bundler and the Gemfile at http://bundler.io

**Comment by irodrigo17** [comment]
This should be fixed by https://github.com/bemyeyes/bemyeyes-ios/pull/20

**Comment by mamaral** [comment]
Thanks @irodrigo17, that seemed to solve the above issue, although now I'm getting:

'ld: library not found for -lPods-BeMyEyes-AFNetworking`

Digging into that to see what the deal is.

**Comment by irodrigo17** [comment]
@mamaral I experienced that too, however it builds just fine if I switch to the BeMyEyes Development target, the default target still needs to be fixed though, but at least you can start playing around with the app.

**Comment by mamaral** [comment]
Awesome - will try tomorrow. Thanks!

**Comment by duemunk** [comment]
You don't need to run `pod install` since the pods are already in the repo. The readme has been updated to reflect this.

**Comment by mamaral** [comment]
Cloning the repo fresh, ***not*** running pod install, and changing the
