### ISSUE TITLE
Having a facebook app installed but unfilled settings fails to authenticate.

### ISSUE THREAD

**Issue by sudheesh001** [bemyeyes/bemyeyes-ios#18]
Many applications which use facebook authentication redirect to the installed facebook app on click for login rather than using the credentials that are put up in the settings section of the app. Having a filled in facebook settings section becomes a mandatory for this app.

**Comment by Thelle** [comment]
Yes we get a lot of support requests about this..! Maybe it's already fixed @duemunk?

**Comment by duemunk** [comment]
Yep, the app only uses the built-in iOS account. In short I think the Facebook SDK is too large for a small feature like logging in. We merely use Facebook as a convenience, so it isn't a deal-breaker to have full support.

Also, the crash-bug is fixed and will be in the next version rolling out soon.

**Comment by Thelle** [comment]
I agree. 
We could add to the text "Please add your account in the system settings..." +THIS: "..or sign up with email"..

It's not possible to link to facebook settings right?
