### ISSUE TITLE
Profile photo for non-facebook users

### ISSUE THREAD

**Issue by sudheesh001** [bemyeyes/bemyeyes-ios#19]
There's no way currently present in the app to upload a photograph onto the user profile. I think it'd be a great feature to add to the options that show up when the gear icon to the top left corner is tapped.

**Comment by Thelle** [comment]
Yes it's on the road map :+1:

**Comment by duemunk** [comment]
Fixed in 5fa3b35eb0aefe2d476758efe06d79967f879d47
