### ISSUE TITLE
Adapt interface to high contrast accessibility option

### ISSUE THREAD

**Issue by duemunk** [bemyeyes/bemyeyes-ios#57]
Ideas:
- [ ] Use black background instead of blue gradient

**Comment by duemunk** [comment]
This doesn't seem to be possible with the current version of iOS https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIKitFunctionReference/index.html. There are option for VoiceOver, and InvertedColors (UIAccessibilityIsInvertColorsEnabled)

**Comment by Thelle** [comment]
Ok - in that case I think the case can be closed..
