### ISSUE TITLE
App crashes on first use

### ISSUE THREAD

**Issue by muddermanden** [bemyeyes/bemyeyes-ios#6]
On iPhone 4 (iOS 7.0.6) the app crashed on first use after asking permission to use the microphone. After pressing Allow, the app crashed. I have not used the app afterwards, hence I cannot say if the problem persists.

**Comment by Thelle** [comment]
The app should only be available for iPhone 4s & iPad 2 and newer devices! Could you check the AppStore/iTunesConnect settings @duemunk or @simonbs?

**Comment by simonbs** [comment]
The deployment target has been updated to iOS 8. This should be corrected in a future release. https://github.com/bemyeyes/bemyeyes-ios/commit/2462a32fd6136beac4b0caf7d4e49176a50ff94f

**Comment by Thelle** [comment]
Just to be clear - so no iOS 7 support? Where can I see the number of iOS 7 users in our userbase @simonbs?
