### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by bguidolim** [bemyeyes/bemyeyes-ios#7]
Hi!

I'm trying to fix issue #6, so I've forked the repo, but I didn't find file ```BeMyEyes-Swift.h```. Could give some help with it?

Also, I suggest to remove ```Pods``` folder from repo.

**Comment by duemunk** [comment]
Hi @bguidolim, thanks for chiming in!

The `BeMyEyes-Swift.h` is an auto-generated header file when you build the project. It exposes the Swift code to Objective-C.

As for CocoaPods I'm the left-wing, so I won't remove folder form the repo :)
