### ISSUE TITLE
Show access permission before demo call. Else notification want show

### ISSUE THREAD

**Issue by duemunk** [bemyeyes/bemyeyes-ios#71]
I tested this on a new device, where the notification didn't show because the user hadn't given access yet. 

Option 1: Show access permissions screen before demo call
Option 2: Ask for a barebones to whatever is necessary for demo call to work 
Option 3: Ideas?

**Comment by duemunk** [comment]
@simonbs

**Comment by simonbs** [comment]
I think we should ask users to enable notifications on the demo call screen as it's launched from the "Welcome" screen. We don't want to much to get in the way.

**Comment by duemunk** [comment]
True.
But it seems more suited to be able to a demo call _after_ things have been setup?

**Comment by simonbs** [comment]
Yes and no. Giving users the option to try making a call before bothering them with too many configurations, may convince them to setup everything.

I'm unsure what the proper solution is. I understand why it makes sense to present the configuration screen first but I'ld also like to see the demo screen being presented as early as possible. I think this gives users a nice "head first" start.

Anyways, I have added a check to DemoCallViewController which means we can present the configuration screen before or after - the controller doesn't really care anymore. It displays a message asking users to enable notifications if they have not already done so.

**Comment by duemunk** [comment]
Ok. I actually also have some commits locally for this. Can you push yours, then I'll merge my stuff in to it.

**Comment by simonbs** [comment]
You'll find it here. 21e634bb7fefe204946a96c97005e4c918189031
